name: Publish package to PyPI

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/develop' || (github.ref == 'refs/heads/main' && contains(github.event.release.tag_name, 'last-release'))

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry env use python
        poetry install

    - name: Build and publish package
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.WEB_AUTH_PYPI_TOKEN_PYPI }}
      run: |
        poetry build
        poetry publish
